const argentinaClubs = [
    { id: "boca_juniors", nameAr: "بوكا جونيورز", nameEn: "Boca Juniors", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10077.png", members: 0, points: 0, color: "linear-gradient(135deg, #00285e, #fdb913)" },
    { id: "river_plate", nameAr: "ريفر بليت", nameEn: "River Plate", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9860.png", members: 0, points: 0, color: "linear-gradient(135deg, #ffffff, #e30613)" },
    { id: "racing_club", nameAr: "راسينغ كلوب", nameEn: "Racing Club", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10103.png", members: 0, points: 0, color: "linear-gradient(135deg, #75b2dd, #ffffff)" },
    { id: "independiente", nameAr: "إنديبندينتي", nameEn: "Independiente", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10076.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #ffffff)" },
    { id: "san_lorenzo", nameAr: "سان لورينزو", nameEn: "San Lorenzo", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10101.png", members: 0, points: 0, color: "linear-gradient(135deg, #00285e, #e30613)" },
    { id: "estudiantes", nameAr: "إستوديانتيس", nameEn: "Estudiantes", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10078.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #ffffff)" },
    { id: "velez", nameAr: "فيليز سارسفيلد", nameEn: "Velez", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10104.png", members: 0, points: 0, color: "linear-gradient(135deg, #ffffff, #00285e)" },
    { id: "rosario_central", nameAr: "روزاريو سنترال", nameEn: "Rosario Central", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10100.png", members: 0, points: 0, color: "linear-gradient(135deg, #00285e, #ffcc00)" },
    { id: "newells", nameAr: "نيولز أولد بويز", nameEn: "Newells Old Boys", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10085.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #000000)" },
    { id: "talleres", nameAr: "تاليريس", nameEn: "Talleres", countryFlag: "🇦🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10128.png", members: 0, points: 0, color: "linear-gradient(135deg, #00285e, #ffffff)" }
];
