const brazilClubs = [
    { id: "flamengo", nameAr: "فلامنغو", nameEn: "Flamengo", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10014.png", members: 0, points: 0, color: "linear-gradient(135deg, #c3281e, #000000)" },
    { id: "palmeiras", nameAr: "بالميراس", nameEn: "Palmeiras", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10214.png", members: 0, points: 0, color: "linear-gradient(135deg, #006437, #ffffff)" },
    { id: "sao_paulo", nameAr: "ساو باولو", nameEn: "Sao Paulo", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9770.png", members: 0, points: 0, color: "linear-gradient(135deg, #ff0000, #000000)" },
    { id: "corinthians", nameAr: "كورينثيانز", nameEn: "Corinthians", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9793.png", members: 0, points: 0, color: "linear-gradient(135deg, #000000, #ffffff)" },
    { id: "fluminense", nameAr: "فلومينينسي", nameEn: "Fluminense", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9863.png", members: 0, points: 0, color: "linear-gradient(135deg, #9f022d, #006039)" },
    { id: "gremio", nameAr: "غريميو", nameEn: "Gremio", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9769.png", members: 0, points: 0, color: "linear-gradient(135deg, #0d80bf, #000000)" },
    { id: "internacional", nameAr: "إنترناسيونال", nameEn: "Internacional", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9771.png", members: 0, points: 0, color: "linear-gradient(135deg, #e5053a, #ffffff)" },
    { id: "atletico_mineiro", nameAr: "أتلتيكو مينيرو", nameEn: "Atletico Mineiro", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9776.png", members: 0, points: 0, color: "linear-gradient(135deg, #000000, #ffffff)" },
    { id: "botafogo", nameAr: "بوتافوغو", nameEn: "Botafogo", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9777.png", members: 0, points: 0, color: "linear-gradient(135deg, #000000, #ffffff)" },
    { id: "vasco_da_gama", nameAr: "فاسكو دا غاما", nameEn: "Vasco da Gama", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9781.png", members: 0, points: 0, color: "linear-gradient(135deg, #000000, #ffffff)" },
    { id: "cruzeiro", nameAr: "كروزيرو", nameEn: "Cruzeiro", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9780.png", members: 0, points: 0, color: "linear-gradient(135deg, #003a94, #ffffff)" },
    { id: "santos", nameAr: "سانتوس", nameEn: "Santos", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9792.png", members: 0, points: 0, color: "linear-gradient(135deg, #000000, #ffffff)" },
    { id: "bahia", nameAr: "باهيا", nameEn: "Bahia", countryFlag: "🇧🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9786.png", members: 0, points: 0, color: "linear-gradient(135deg, #003a94, #e5053a)" }
];
