// ==========================================
// 🚀 ملف البيانات (data.js) - Zelo Sport
// يحتوي على قاموس الترجمة والتجميع النهائي للأندية فقط
// ==========================================

const i18n = {
    ar: {
        welcomeTitle: "مرحباً بك في Zelo Sport",
        welcomeSub: "اختر ناديك المفضل للبدء في حصد النقاط",
        navHome: "الرئيسية",
        navTasks: "المهام",
        navFriends: "الأصدقاء",
        navLeaderboard: "الترتيب",
        navWallet: "المحفظة",
        coins: "عملة:",
        yourClub: "ناديك:",
        clubLocked: "✔ ناديك الثابت 🔒",
        fans: "مشجع",
        supportText: "أنت تشجع فريق:",
        allClubsTitle: "🏟️ ترتيب الأندية الكبرى",
        lockedNotice: "تم تثبيت ناديك بنجاح. لا يمكن التبديل لضمان المنافسة العادلة 🔒.",
        dailyCheckin: "📆 تسجيل الدخول اليومي",
        dailyCheckinSub: "احصل على 200 عملة مجانية فورية لدعم ناديك!",
        btnClaim: "استلام",
        btnClaimed: "تم",
        currentTasks: "🔥 قائمة المهام الحالية",
        btnGo: "انتقال",
        btnDone: "✓ تم",
        alertTaskDone: "ممتاز! أكملت المهمة بنجاح وحصلت على",
        alertDailyDone: "تم استلام مكافأة الحضور اليومي بنجاح (+200 عملة).",
        referralTitle: "👥 نظام الإحالات ودعوة الكتائب",
        referralSub: "انشر رابطك؛ لكل مشجع جديد يدخل التطبيق عبر معرف التليجرام الخاص بك تكسب أنت وناديك 500 عملة.",
        btnCopy: "📋 نسخ الرابط",
        btnShare: "✈️ مشاركة",
        friendsList: "قائمة الأصدقاء المنضمين",
        invites: "دعواته:",
        alertCopied: "تم نسخ الرابط بنجاح!",
        shareText: "⚽ اختر ناديك المفضل في Zilo FC واجمع معي العملات والجوائز الرقمية مجاناً! 🏆",
        leaderTitle: "🏆 صدارة بطولة الكأس الأوروبي",
        leaderSub: "انقر على أي فريق لفتح قائمة ترتيب أعلى المشجعين تجميعاً للنقاط.",
        clickToView: "👉 اضغط لرؤية المتصدرين",
        btnBack: "⬅ عودة لقائمة الأندية الكلية",
        topFansOf: "ترتيب متصدري جماهير",
        topFansSub: "تظهر هذه اللوحة ترتيب المشجعين الأكثر نشاطاً.",
        colRank: "المركز",
        colFan: "المشجع",
        colPoints: "النقاط",
        colActivity: "النشاط",
        referralWord: "إحالة",
        walletConnected: "المحفظة الحقيقية متصلة",
        walletBalance: "رصيد TON في المحفظة",
        btnCopyAddress: "📋 نسخ العنوان",
        btnDisconnect: "🚪 إلغاء الربط",
        walletConnectTitle: "ربط محفظة Web3 الحقيقية",
        walletConnectSub: "قم بربط محفظة التليجرام الآمنة الحقيقية لاستقبال مكافآت عملات Zilo FC.",
        btnConnect: "💎 اتصل بمحفظتك الحقيقية (TON Connect)",
        alertDisconnect: "هل تريد قطع اتصال المحفظة الحالية؟",
        alertDisconnected: "تم قطع الاتصال بنجاح."
    },
    en: {
        welcomeTitle: "Welcome to Zelo Sport",
        welcomeSub: "Choose your favorite club to start earning points",
        navHome: "Home",
        navTasks: "Tasks",
        navFriends: "Friends",
        navLeaderboard: "Ranking",
        navWallet: "Wallet",
        coins: "Coins:",
        yourClub: "Club:",
        clubLocked: "✔ Locked 🔒",
        fans: "Fans",
        supportText: "You support:",
        allClubsTitle: "🏟️ Top Clubs Ranking",
        lockedNotice: "Your club is locked. Switching is disabled for fair competition 🔒.",
        dailyCheckin: "📆 Daily Check-in",
        dailyCheckinSub: "Get 200 free coins instantly to support your club!",
        btnClaim: "Claim",
        btnClaimed: "Claimed",
        currentTasks: "🔥 Current Tasks",
        btnGo: "Go",
        btnDone: "✓ Done",
        alertTaskDone: "Excellent! Task completed, you received",
        alertDailyDone: "Daily reward claimed successfully (+200 Coins).",
        referralTitle: "👥 Referral System",
        referralSub: "Share your link! For every new fan joining via your ID, you and your club earn 500 coins.",
        btnCopy: "📋 Copy Link",
        btnShare: "✈️ Share",
        friendsList: "Joined Friends List",
        invites: "Invites:",
        alertCopied: "Link copied successfully!",
        shareText: "⚽ Choose your favorite club in Zelo Sport and collect crypto rewards with me for free! 🏆",
        leaderTitle: "🏆 European Cup Leaderboard",
        leaderSub: "Click on any team to view its top fans by points.",
        clickToView: "👉 Click to view top fans",
        btnBack: "⬅ Back to Clubs",
        topFansOf: "Top fans of",
        topFansSub: "This board shows fans who collected the most points.",
        colRank: "Rank",
        colFan: "Fan",
        colPoints: "Points",
        colActivity: "Activity",
        referralWord: "Referrals",
        walletConnected: "Real Wallet Connected",
        walletBalance: "TON Balance",
        btnCopyAddress: "📋 Copy Address",
        btnDisconnect: "🚪 Disconnect",
        walletConnectTitle: "Connect Web3 Real Wallet",
        walletConnectSub: "Connect your secure Telegram Wallet to receive Zilo FC token rewards.",
        btnConnect: "💎 Connect Real Wallet (TON Connect)",
        alertDisconnect: "Do you want to disconnect the current wallet?",
        alertDisconnected: "Disconnected successfully."
    }
};

// ==========================================
// التجميع النهائي لجميع الأندية من جميع الدول (48 ملف)
// ==========================================
const clubsData = [
    ...argentinaClubs,
    ...franceClubs,
    ...brazilClubs,
    ...englandClubs,
    ...germanyClubs,
    ...spainClubs,
    ...italyClubs,
    ...portugalClubs,
    ...netherlandsClubs,
    ...belgiumClubs,
    ...uruguayClubs,
    ...colombiaClubs,
    ...mexicoClubs,
    ...usaClubs,
    ...canadaClubs,
    ...japanClubs,
    ...southKoreaClubs,
    ...saudiArabiaClubs,
    ...uaeClubs,
    ...syriaClubs,
    ...qatarClubs,
    ...moroccoClubs,
    ...egyptClubs,
    ...tunisiaClubs,
    ...algeriaClubs,
    ...iranClubs,
    ...iraqClubs,
    ...australiaClubs,
    ...croatiaClubs,
    ...switzerlandClubs,
    ...denmarkClubs,
    ...polandClubs,
    ...serbiaClubs,
    ...austriaClubs,
    ...turkeyClubs,
    ...ecuadorClubs,
    ...chileClubs,
    ...paraguayClubs,
    ...peruClubs,
    ...nigeriaClubs,
    ...ghanaClubs,
    ...senegalClubs,
    ...cameroonClubs,
    ...ivoryCoastClubs,
    ...greeceClubs,
    ...swedenClubs,
    ...norwayClubs,
    ...hungaryClubs
];
