const englandClubs = [
    { id: "man_city", nameAr: "مانشستر سيتي", nameEn: "Man City", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8456.png", members: 0, points: 0, color: "linear-gradient(135deg, #81d4fa, #4fc3f7)" },
    { id: "arsenal", nameAr: "أرسنال", nameEn: "Arsenal", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9825.png", members: 0, points: 0, color: "linear-gradient(135deg, #d50000, #b71c1c)" },
    { id: "liverpool", nameAr: "ليفربول", nameEn: "Liverpool", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8650.png", members: 0, points: 0, color: "linear-gradient(135deg, #c62828, #b71c1c)" },
    { id: "man_united", nameAr: "مانشستر يونايتد", nameEn: "Man United", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8654.png", members: 0, points: 0, color: "linear-gradient(135deg, #da291c, #000000)" },
    { id: "chelsea", nameAr: "تشيلسي", nameEn: "Chelsea", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8455.png", members: 0, points: 0, color: "linear-gradient(135deg, #034694, #000000)" },
    { id: "tottenham", nameAr: "توتنهام", nameEn: "Tottenham", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8586.png", members: 0, points: 0, color: "linear-gradient(135deg, #ffffff, #132257)" },
    { id: "newcastle", nameAr: "نيوكاسل", nameEn: "Newcastle", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10261.png", members: 0, points: 0, color: "linear-gradient(135deg, #000000, #ffffff)" },
    { id: "aston_villa", nameAr: "أستون فيلا", nameEn: "Aston Villa", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10252.png", members: 0, points: 0, color: "linear-gradient(135deg, #7a003c, #95bfe5)" },
    { id: "west_ham", nameAr: "وست هام", nameEn: "West Ham", countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8659.png", members: 0, points: 0, color: "linear-gradient(135deg, #7a263a, #1bb1e7)" }
];
