const franceClubs = [
    { id: "psg", nameAr: "باريس سان جيرمان", nameEn: "PSG", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9847.png", members: 0, points: 0, color: "linear-gradient(135deg, #004170, #da291c)" },
    { id: "marseille", nameAr: "مارسيليا", nameEn: "Marseille", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8592.png", members: 0, points: 0, color: "linear-gradient(135deg, #009ee0, #ffffff)" },
    { id: "lyon", nameAr: "ليون", nameEn: "Lyon", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9748.png", members: 0, points: 0, color: "linear-gradient(135deg, #da291c, #004170)" },
    { id: "monaco", nameAr: "موناكو", nameEn: "Monaco", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9829.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #ffffff)" },
    { id: "lille", nameAr: "ليل", nameEn: "Lille", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8639.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #000040)" },
    { id: "lens", nameAr: "لانس", nameEn: "Lens", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8588.png", members: 0, points: 0, color: "linear-gradient(135deg, #ed1c24, #ffc20e)" },
    { id: "rennes", nameAr: "رين", nameEn: "Rennes", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8583.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #000000)" },
    { id: "nice", nameAr: "نيس", nameEn: "Nice", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9827.png", members: 0, points: 0, color: "linear-gradient(135deg, #da291c, #000000)" },
    { id: "reims", nameAr: "ريمس", nameEn: "Reims", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9830.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #ffffff)" },
    { id: "strasbourg", nameAr: "ستراسبورغ", nameEn: "Strasbourg", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9831.png", members: 0, points: 0, color: "linear-gradient(135deg, #0053a0, #ffffff)" },
    { id: "toulouse", nameAr: "تولوز", nameEn: "Toulouse", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9941.png", members: 0, points: 0, color: "linear-gradient(135deg, #4b2383, #ffffff)" },
    { id: "montpellier", nameAr: "مونبلييه", nameEn: "Montpellier", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8690.png", members: 0, points: 0, color: "linear-gradient(135deg, #003882, #f47920)" },
    { id: "nantes", nameAr: "نانت", nameEn: "Nantes", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9830.png", members: 0, points: 0, color: "linear-gradient(135deg, #008000, #ffff00)" },
    { id: "brest", nameAr: "بريست", nameEn: "Brest", countryFlag: "🇫🇷", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8550.png", members: 0, points: 0, color: "linear-gradient(135deg, #e30613, #ffffff)" }
];
