const germanyClubs = [
    { id: "bayern", nameAr: "بايرن ميونخ", nameEn: "Bayern Munich", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9823.png", members: 0, points: 0, color: "linear-gradient(135deg, #d50000, #b71c1c)" },
    { id: "dortmund", nameAr: "دورتموند", nameEn: "Dortmund", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9789.png", members: 0, points: 0, color: "linear-gradient(135deg, #fde100, #000000)" },
    { id: "leverkusen", nameAr: "باير ليفركوزن", nameEn: "Leverkusen", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8171.png", members: 0, points: 0, color: "linear-gradient(135deg, #e32221, #000000)" },
    { id: "leipzig", nameAr: "لايبزيغ", nameEn: "RB Leipzig", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/178475.png", members: 0, points: 0, color: "linear-gradient(135deg, #dd013f, #ffffff)" },
    { id: "frankfurt", nameAr: "آينتراخت فرانكفورت", nameEn: "Frankfurt", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9810.png", members: 0, points: 0, color: "linear-gradient(135deg, #e1000f, #000000)" },
    { id: "stuttgart", nameAr: "شتوتجارت", nameEn: "Stuttgart", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/10269.png", members: 0, points: 0, color: "linear-gradient(135deg, #e32221, #ffffff)" },
    { id: "monchengladbach", nameAr: "مونشنغلادباخ", nameEn: "Monchengladbach", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9788.png", members: 0, points: 0, color: "linear-gradient(135deg, #000000, #ffffff)" },
    { id: "wolfsburg", nameAr: "فولفسبورغ", nameEn: "Wolfsburg", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9721.png", members: 0, points: 0, color: "linear-gradient(135deg, #009d4e, #ffffff)" },
    { id: "hoffenheim", nameAr: "هوفنهايم", nameEn: "Hoffenheim", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8226.png", members: 0, points: 0, color: "linear-gradient(135deg, #005f9e, #ffffff)" },
    { id: "freiburg", nameAr: "فرايبورغ", nameEn: "Freiburg", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8358.png", members: 0, points: 0, color: "linear-gradient(135deg, #d11919, #000000)" },
    { id: "union_berlin", nameAr: "يونيون برلين", nameEn: "Union Berlin", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8149.png", members: 0, points: 0, color: "linear-gradient(135deg, #d30d1f, #e5c300)" },
    { id: "werder_bremen", nameAr: "فيردر بريمن", nameEn: "Werder Bremen", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8697.png", members: 0, points: 0, color: "linear-gradient(135deg, #1d8438, #ffffff)" },
    { id: "augsburg", nameAr: "أوغسبورغ", nameEn: "Augsburg", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/8406.png", members: 0, points: 0, color: "linear-gradient(135deg, #ba131a, #005d3a)" },
    { id: "mainz", nameAr: "ماينز", nameEn: "Mainz 05", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9905.png", members: 0, points: 0, color: "linear-gradient(135deg, #ed1c24, #ffffff)" },
    { id: "bochum", nameAr: "بوخوم", nameEn: "VfL Bochum", countryFlag: "🇩🇪", logo: "https://images.fotmob.com/image_resources/logo/teamlogo/9911.png", members: 0, points: 0, color: "linear-gradient(135deg, #005ca9, #ffffff)" }
];
